
export default {
	AUTH_START: 'AUTH_START',
	AUTH_COMPLETE: 'AUTH_COMPLETE',
	AUTH_ERROR: 'AUTH_ERROR',
	AUTH_CHECK: 'AUTH_CHECK',
	LOGOUT_START: 'LOGOUT_START',

	LOGIN_PAGE_SET_EMAIL: 'LOGIN_PAGE_SET_EMAIL',
	LOGIN_PAGE_SET_PW: 'LOGIN_PAGE_SET_PW',

	HOME_PAGE_UPDATE_POSTS: 'HOME_PAGE_UPDATE_POSTS',

	POST_PAGE_UPDATE: 'POST_PAGE_UPDATE',
	
	MODALNORMAL_SHOW: 'MODALNORMAL_SHOW',
	MODALNORMAL_HIDE: 'MODALNORMAL_HIDE',

	STORAGE_GET_POST_MENU: 'STORAGE_GET_POST_MENU',
	STORAGE_GET_POST: 'STORAGE_GET_POST'
}
